### PR TITLE
fix: archive reading file size limit issue

### PR DESCRIPTION
**Pull request by grighakobian**

### CODE REVIEW

**Review by HomanFa — APPROVED** [review]

**Comment by mickael-menu** [comment]
Could you share a bit about the issue you had with this check? Maybe there's something to update upstream in Readium.

Note that removing this fix might cause crashes in production due to out of memory errors, so it's not recommended.

**Comment by grighakobian** [comment]
Hi Mickael,

Several users reported issues with playing a book. Upon investigation, I discovered that the book archive contains .mp3 files larger than 5 MB. To address this, I've temporarily skipped the archive entry size limit.

I suggest making the archive entry size limit configurable in the future. However, I currently don't have the bandwidth to implement that change.

**Comment by mickael-menu** [comment]
I don't understand how that would help, did you check that it was fixed with this workaround?

This code is run when trying to figure out the media type of an unknown file. This is used to read the whole content of a JSON file for example, but we don't want to read a binary file entirely in memory, hence the check. And this is executed only for a file on the disk with no recognizable file extensions, not for archive entries.

**Comment by grighakobian** [comment]
Thanks for pointing out the specific use-case of the code. I've taken a deeper look into the problem. The book which users couldn't play contained both jpg and pdf files. I adjusted the MediaType archive sniffer to ignore these files.

However, further investigation revealed an additional issue: there's a scenario where MediaTypeSnifferContext contentAsArchive is nil. My tests indicated that this issue arises due to the FileMediaTypeSnifferContent read size limit. By ignoring the archive entry size limit, I aimed to tackle this latter problem.

I hope this provides a clearer understanding of the steps I took. Let me know if you have further questions or if there's anything else I can assist with.


Screenshot 2023-10-01 at 14 32 36
Screenshot 2023-10-01 at 14 32 44
Screenshot 2023-10-01 at 14 32 55

**Comment by mickael-menu** [comment]
I'm still a bit confused as to why `contentAsArchive` would be nil if it's a valid ZIP archive and it's on the local file system. Would you mind sharing the file with me, privately if needed? Thanks!

**Comment by grighakobian** [comment]
@mickael-menu I have uploaded the audio archive to my Dropbox account, you can download using this link https://www.dropbox.com/scl/fi/a921d12wmt012mopwip0v/9780141356228.zip?rlkey=gcsjay7mc1usrzk3yuggpj8zv&dl=0.

**Comment by mickael-menu** [comment]
Thanks @grighakobian, I added `jpg` to the extensions allowlist and I could open this book successfully without removing the 5MB check.

I will think about adding bitmaps and maybe `pdf` to the allowlist for audiobooks in Readium.

**Comment by mickael-menu** [comment]
By the way I realized why `contentAsArchive` was nil, it's normal. The sniffers are run a first time for a "lightweight" sniffing step with only file extensions and media type hints. Then a second time with the actual content, in which case `contentAsArchive` is not `nil` anymore.

**Comment by grighakobian** [comment]
@mickael-menu  Good job!, thanks.

**Pull request merged**
